#!/usr/bin/env python3
"""
Turn the traced logo into the emblem the site uses.

original-logo-traced.svg is faithful to the printed card, but it is an
auto-trace of a photograph and carries two flaws from that:

  * the card was photographed slightly askew, so the whole mark is rotated;
  * the two halves do not match — the lower bow limb is thinner than the
    upper, the lower-right string is broken, and the lower wreath carries
    specks the upper does not.

The mark is meant to be upright and symmetric about its horizontal axis, so
this script measures the rotation that makes it most symmetric, straightens it
by that much, then keeps the cleaner upper half and mirrors it downward. That
fixes the tilt and the asymmetry and drops the lower-half noise, while keeping
the authentic leaf and limb shapes from the trace.

Order matters: straighten first, then mirror. Mirroring a tilted mark about a
horizontal axis leaves the halves tilted opposite ways, which reads as a subtle
bowtie rather than as a logo.

    python3 tools/build-emblem.py > /tmp/emblem.svg
"""
import re
import sys
from pathlib import Path

import numpy as np

# Quarter-turns clockwise applied to the finished mark. The straighten-and-
# mirror step below works on a horizontal symmetry axis, so the turn is applied
# afterwards, to the composed result, rather than folded into `theta`.
TURNS = int(sys.argv[sys.argv.index('--turn') + 1]) % 4 if '--turn' in sys.argv else 0
_files = [a for a in sys.argv[1:] if not a.startswith('--') and not a.isdigit()]
SRC = Path(_files[0]) if _files else Path(__file__).with_name('original-logo-traced.svg')
paths = re.findall(r'<path d="([^"]+)"', SRC.read_text())

pts = []
for d in paths:
    n = [float(v) for v in re.findall(r'-?\d+\.?\d*', d)]
    pts += list(zip(n[0::2], n[1::2]))
P = np.array(pts, float)
centre = P.mean(axis=0)
Q0 = P - centre
span = np.abs(Q0).max() * 1.05
GRID = 160


def _raster(Q):
    ix = ((Q[:, 0] + span) / (2 * span) * (GRID - 1)).astype(int)
    iy = ((Q[:, 1] + span) / (2 * span) * (GRID - 1)).astype(int)
    ok = (ix >= 0) & (ix < GRID) & (iy >= 0) & (iy < GRID)
    a = np.zeros((GRID, GRID), bool)
    a[iy[ok], ix[ok]] = True
    out = a.copy()
    for dy in (-1, 0, 1):
        for dx in (-1, 0, 1):
            out |= np.roll(np.roll(a, dy, 0), dx, 1)
    return out


def symmetry(theta_deg, axis_dy):
    """How well the mark mirrors onto itself, as intersection over union."""
    t = np.radians(theta_deg)
    R = np.array([[np.cos(t), -np.sin(t)], [np.sin(t), np.cos(t)]])
    Q = Q0 @ R.T - np.array([0.0, axis_dy])
    A, B = _raster(Q), _raster(Q * np.array([1.0, -1.0]))
    union = (A | B).sum()
    return (A & B).sum() / union if union else 0.0


def best_alignment():
    best = (0.0, 0.0, -1.0)
    for theta in np.arange(-20, 20.01, 0.5):
        for dy in np.arange(-24, 24.1, 4):
            s = symmetry(theta, dy)
            if s > best[2]:
                best = (theta, dy, s)
    t0, d0, _ = best
    for theta in np.arange(t0 - 0.6, t0 + 0.61, 0.05):
        for dy in np.arange(d0 - 5, d0 + 5.1, 0.5):
            s = symmetry(theta, dy)
            if s > best[2]:
                best = (theta, dy, s)
    return best


theta, axis_dy, score = best_alignment()
cx, cy = centre
axis_y = cy + axis_dy

# the straightened outline, used only to size the viewBox
t = np.radians(theta)
R = np.array([[np.cos(t), -np.sin(t)], [np.sin(t), np.cos(t)]])
S = Q0 @ R.T + centre
# the visible mark is the upper half plus its mirror, so it reaches as far below
# the axis as the upper half reaches above it
top = S[:, 1].min()
reach = axis_y - top
x0, x1 = S[:, 0].min(), S[:, 0].max()
half = max((x1 - x0) / 2, reach) * 1.06
vx, vy = (x0 + x1) / 2 - half, axis_y - half

body = '\n'.join(f'      <path d="{d}"/>' for d in paths)

cx_v, cy_v = vx + half, vy + half   # centre of the square viewBox

print(f'''<!-- generated by tools/build-emblem.py — do not hand-edit
     straightened by {theta:+.2f}°, mirrored about y={axis_y:.1f}, turned {TURNS * 90}° clockwise
     symmetry {symmetry(0, 0):.3f} -> {score:.3f} -->
<svg viewBox="{vx:.1f} {vy:.1f} {2 * half:.1f} {2 * half:.1f}" fill="CLR" fill-rule="evenodd" aria-hidden="true" focusable="false">
  <defs>
    <clipPath id="pc-half">
      <rect x="{vx - half:.1f}" y="{vy - half:.1f}" width="{4 * half:.1f}" height="{axis_y - vy + half:.1f}"/>
    </clipPath>
    <g id="pc-art" transform="rotate({theta:.2f} {cx:.1f} {cy:.1f})">
{body}
    </g>
    <g id="pc-mark">
      <g clip-path="url(#pc-half)"><use href="#pc-art"/></g>
      <g clip-path="url(#pc-half)" transform="translate(0 {2 * axis_y:.1f}) scale(1 -1)"><use href="#pc-art"/></g>
    </g>
  </defs>
  <use href="#pc-mark" transform="rotate({TURNS * 90} {cx_v:.1f} {cy_v:.1f})"/>
</svg>''')
